<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <RootNamespace>HospitalBilling</RootNamespace>
    <AssemblyName>HospitalBilling</AssemblyName>
    <StartupObject>HospitalBilling.Form1</StartupObject>
  </PropertyGroup>

</Project>
