-- =====================================================
-- SUPABASE POSTGRESQL SCHEMA — SMART HEALTHCARE & DIAGNOSTIC MANAGEMENT SYSTEM
-- =====================================================
-- Compatible with PostgreSQL 14+ / Supabase
-- =====================================================

-- Clean up existing tables in reverse dependency order
DROP TABLE IF EXISTS warnings CASCADE;
DROP TABLE IF EXISTS activity_log CASCADE;
DROP TABLE IF EXISTS remember_tokens CASCADE;
DROP TABLE IF EXISTS billing CASCADE;
DROP TABLE IF EXISTS diagnosis_rules CASCADE;
DROP TABLE IF EXISTS appointments CASCADE;
DROP TABLE IF EXISTS doctors CASCADE;
DROP TABLE IF EXISTS patients CASCADE;
DROP TABLE IF EXISTS users CASCADE;

-- =====================================================
-- TABLE 1: users
-- Central authentication table for all 3 roles: patient, doctor, admin
-- =====================================================
CREATE TABLE users (
    user_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_name VARCHAR(100) NOT NULL,
    email VARCHAR(100) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    role VARCHAR(20) NOT NULL CHECK (role IN ('patient', 'doctor', 'admin')),
    phone VARCHAR(20) NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'suspended')),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- =====================================================
-- TABLE 2: patients
-- Profile details for role = 'patient'
-- =====================================================
CREATE TABLE patients (
    patient_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(user_id) ON DELETE CASCADE,
    age INT NOT NULL CHECK (age >= 1 AND age <= 120),
    weight NUMERIC(5,2) NOT NULL,
    cnic VARCHAR(15) NOT NULL,
    insurance_number VARCHAR(50) DEFAULT NULL
);

-- =====================================================
-- TABLE 3: doctors
-- Profile details and schedule for role = 'doctor'
-- =====================================================
CREATE TABLE doctors (
    doctor_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(user_id) ON DELETE CASCADE,
    specialization VARCHAR(100) NOT NULL,
    clinic_address VARCHAR(255) DEFAULT NULL,
    city VARCHAR(100) DEFAULT NULL,
    available_from TIME DEFAULT '09:00:00',
    available_to TIME DEFAULT '17:00:00',
    consultation_fee NUMERIC(10,2) DEFAULT 500.00
);

-- =====================================================
-- TABLE 4: appointments
-- Patient appointment bookings with severity and status
-- =====================================================
CREATE TABLE appointments (
    appointment_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    patient_id BIGINT NOT NULL REFERENCES patients(patient_id) ON DELETE CASCADE,
    doctor_id BIGINT NOT NULL REFERENCES doctors(doctor_id) ON DELETE CASCADE,
    severity_level VARCHAR(20) NOT NULL CHECK (severity_level IN ('Emergency', 'Normal', 'Follow-up')),
    appointment_time TIMESTAMPTZ NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'Pending' CHECK (status IN ('Pending', 'Confirmed', 'Completed', 'Cancelled')),
    symptoms_selected VARCHAR(500) DEFAULT NULL,
    symptoms_text TEXT DEFAULT NULL,
    diagnosed_disease VARCHAR(100) DEFAULT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- =====================================================
-- TABLE 5: diagnosis_rules
-- Rule engine mapping symptoms to diseases and emergency advice
-- =====================================================
CREATE TABLE diagnosis_rules (
    rule_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    symptom_combination VARCHAR(500) NOT NULL,
    possible_disease VARCHAR(100) NOT NULL,
    advice TEXT NOT NULL,
    recommended_specialization VARCHAR(100) DEFAULT 'General Physician',
    is_emergency BOOLEAN DEFAULT FALSE,
    first_aid_steps TEXT DEFAULT NULL
);

-- =====================================================
-- TABLE 6: billing
-- Invoice records with automatic 20% insurance discount calculation
-- =====================================================
CREATE TABLE billing (
    bill_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    appointment_id BIGINT NOT NULL REFERENCES appointments(appointment_id) ON DELETE CASCADE,
    consultation_fee NUMERIC(10,2) NOT NULL DEFAULT 0.00,
    test_charges NUMERIC(10,2) NOT NULL DEFAULT 0.00,
    insurance_discount_percent NUMERIC(5,2) NOT NULL DEFAULT 0.00,
    total_amount NUMERIC(10,2) NOT NULL DEFAULT 0.00,
    payment_status VARCHAR(20) NOT NULL DEFAULT 'Unpaid' CHECK (payment_status IN ('Unpaid', 'Paid')),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- =====================================================
-- TABLE 7: remember_tokens
-- 30-Day split-token authentication storage
-- =====================================================
CREATE TABLE remember_tokens (
    token_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(user_id) ON DELETE CASCADE,
    selector VARCHAR(32) NOT NULL UNIQUE,
    hashed_validator VARCHAR(64) NOT NULL,
    expires_at TIMESTAMPTZ NOT NULL
);

-- =====================================================
-- TABLE 8: activity_log
-- Audit trail for all system activities
-- =====================================================
CREATE TABLE activity_log (
    log_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(user_id) ON DELETE CASCADE,
    action VARCHAR(100) NOT NULL,
    details VARCHAR(255) DEFAULT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- =====================================================
-- TABLE 9: warnings
-- Admin warning notifications to users
-- =====================================================
CREATE TABLE warnings (
    warning_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(user_id) ON DELETE CASCADE,
    message TEXT NOT NULL,
    is_read BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- =====================================================
-- TABLE 10: php_sessions
-- Serverless Session Store (Persists reliably across Vercel invocations)
-- =====================================================
CREATE TABLE php_sessions (
    id VARCHAR(128) PRIMARY KEY,
    data TEXT NOT NULL,
    last_activity TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- =====================================================
-- SEED DATA: 7 Diagnostic Rules
-- =====================================================
INSERT INTO diagnosis_rules (symptom_combination, possible_disease, advice, recommended_specialization, is_emergency, first_aid_steps) VALUES
('fever,cough,body_ache,headache',
 'Flu (Influenza)',
 'Rest well, drink plenty of fluids, and take over-the-counter fever reducers like paracetamol. See a doctor if symptoms persist beyond 3 days or if fever exceeds 103°F.',
 'General Physician', FALSE, NULL),

('fever,cough,shortness_of_breath',
 'Respiratory Infection',
 'Seek medical attention promptly. Avoid smoking and dusty environments. A chest X-ray may be recommended by your doctor. Monitor breathing difficulty closely.',
 'Pulmonologist', FALSE, NULL),

('headache,nausea,sensitivity_to_light',
 'Migraine',
 'Rest in a dark, quiet room. Stay hydrated and avoid screen time. Over-the-counter pain relievers may help. Consult a doctor if migraines occur frequently.',
 'Neurologist', FALSE, NULL),

('stomach_pain,vomiting,diarrhea,nausea',
 'Food Poisoning',
 'Stay hydrated with ORS (oral rehydration salts). Avoid solid food until vomiting stops. Eat bland foods when recovering. Seek medical help if symptoms last more than 24 hours.',
 'Gastroenterologist', FALSE, NULL),

('chest_pain,shortness_of_breath,sweating',
 'Cardiac Issue (Emergency)',
 'SEEK IMMEDIATE EMERGENCY MEDICAL ATTENTION. Do not delay — call an ambulance or go to the nearest emergency room immediately. Do not ignore chest pain combined with breathing difficulty.',
 'Cardiologist', TRUE,
 '1. Call emergency services (1122) or go to the nearest ER immediately.
2. Sit down or lie down in a comfortable position, avoid exertion.
3. Loosen any tight clothing.
4. Stay calm and avoid panic — try slow, steady breathing.
5. Do not drive yourself — have someone else drive or call an ambulance.
6. Do NOT take any medication unless already prescribed by your doctor for this exact condition.'),

('fever,body_ache,rash,joint_pain,headache',
 'Dengue Fever',
 'Seek medical attention immediately. Stay hydrated with fluids. Platelet count monitoring is essential. Use mosquito nets.',
 'General Physician', TRUE,
 '1. Seek immediate medical evaluation at a hospital or clinic.
2. Rest in a comfortable place and stay hydrated with clean water or ORS.
3. Use mosquito nets to prevent further mosquito bites.
4. Monitor closely for warning signs such as severe abdominal pain or bleeding.
5. Do NOT take any unprescribed medications.'),

('sore_throat,fever,swollen_glands,headache',
 'Throat Infection',
 'Gargle with warm salt water 3-4 times daily. Stay hydrated with warm fluids. Avoid cold drinks. Antibiotics may be needed — consult a doctor for proper prescription. Do not self-medicate.',
 'ENT Specialist', FALSE, NULL);

-- =====================================================
-- SEED DATA: 3 Default Test Accounts (password: password123)
-- Hash: $2y$10$e0MYzXyjpJS7Pd0RVvHwHeFjKN.bpKjQ8r8iP17gN5oF9aR.o2jqa
-- =====================================================

-- 1. Admin Account (admin@healthcare.com)
INSERT INTO users (user_id, full_name, email, password, role, phone, status) VALUES
(1, 'System Administrator', 'admin@healthcare.com', '$2y$10$e0MYzXyjpJS7Pd0RVvHwHeFjKN.bpKjQ8r8iP17gN5oF9aR.o2jqa', 'admin', '03001234567', 'active');

-- 2. Patient Account (nasibrehman187@gmail.com)
INSERT INTO users (user_id, full_name, email, password, role, phone, status) VALUES
(2, 'Nasib Rehman', 'nasibrehman187@gmail.com', '$2y$10$e0MYzXyjpJS7Pd0RVvHwHeFjKN.bpKjQ8r8iP17gN5oF9aR.o2jqa', 'patient', '03062320099', 'active');

INSERT INTO patients (patient_id, user_id, age, weight, cnic, insurance_number) VALUES
(1, 2, 24, 68.50, '42201-1234567-1', 'INS-789012');

-- 3. Doctor Account (engrazhariqbal34@gmail.com)
INSERT INTO users (user_id, full_name, email, password, role, phone, status) VALUES
(3, 'Dr. Azhar Iqbal', 'engrazhariqbal34@gmail.com', '$2y$10$e0MYzXyjpJS7Pd0RVvHwHeFjKN.bpKjQ8r8iP17gN5oF9aR.o2jqa', 'doctor', '03009876543', 'active');

INSERT INTO doctors (doctor_id, user_id, specialization, clinic_address, city, available_from, available_to, consultation_fee) VALUES
(1, 3, 'General Physician', 'Clinic #4, Main Medical Plaza', 'Karachi', '14:00:00', '17:00:00', 800.00);

-- Sync Identity sequences to avoid primary key collisions
SELECT setval('users_user_id_seq', (SELECT MAX(user_id) FROM users));
SELECT setval('patients_patient_id_seq', (SELECT MAX(patient_id) FROM patients));
SELECT setval('doctors_doctor_id_seq', (SELECT MAX(doctor_id) FROM doctors));
SELECT setval('diagnosis_rules_rule_id_seq', (SELECT MAX(rule_id) FROM diagnosis_rules));
